### ISSUE TITLE
UI tests doesn't start after update to kotlin 1.5

### ISSUE THREAD

**Issue by Jacks0N23** [allure-framework/allure-kotlin#58]
#### I'm submitting a ... 
  - [x] bug report
  
#### What is the current behavior?
After update to kotlin 1.5 (with useOldBackend = true, because of problems with new IR) test stopped to run. After some investigation I figured out that problem somewhere in allure.

#### If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem
if set: ` testInstrumentationRunner "io.qameta.allure.android.runners.AllureAndroidJUnitRunner"` then tests event not started. But when I replace it with parent of it - ` testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"` then it's run successfully.
I also tested that it's doesn't matter what targer sdk 30 or 29. BUT. Problem only on emulator/device with android 11 (30sdk). With lower everything okay.

#### What is the expected behavior?
Tests starts and run

#### Please tell us about your environment:

| Allure version | 2.2.5 |
| --- | --- |
| kotlin| 1.5(useOldBackend=true)|
| Test framework | junit@4.13.2 |
| Allure integration | allure-kotlin-android@2.2.5 |

#### Other information 

![image](https://user-images.githubusercontent.com/9117565/118482332-438a3e00-b71d-11eb-92ba-bcc271cf800a.png)
![image](https://user-images.githubusercontent.com/9117565/118482392-57ce3b00-b71d-11eb-96fe-0268e18ad887.png)

**Comment by flotnik** [comment]
This problem happens  due to Android 11.

**Comment by viclovsky** [comment]
Hi, @Jacks0N23. 
Could you check the latest version of allure-kotlin (2.2.6), I have merged some fixes.

**Comment by flotnik** [comment]
I have checked on 2.2.6 and test still do not start on Android 11.

**Comment by viclovsky** [comment]
Hi, @flotnik

To be honest I need more information to reproduce your issue. It would be great if you add some example right to GitHub. 
I have checked it locally and it works.
![изображение](https://user-images.githubusercontent.com/20776437/120327881-ed0f2900-c2f2-11eb-9435-914bd6be151a.png)

Thanks.

**Comment by nickmi11er** [comment]
Hi, @viclovsky! I've also tried to bump version to 2.2.6 but the problem stays. 
<img width="1728" alt="Снимок экрана 2021-06-01 в 18 37 27" src="https://user-images.githubusercontent.com/36725714/120352255-46825280-c309-11eb-8153-4b3e1ac177d0.png">

**Comment by flotnik** [comment]
Adding to app manifest MANAGE_EXTERNAL_STORAGE permission solved my problem. With this permission tests are able to start on Android 11 with allure-kotlin:2.2.6

**Comment by nickmi11er** [comment]
@flotnik Thanks! Now it actually works!

**Comment by viclovsky** [comment]
I am closing the issue. I have updated ReadMe with correct [manifest](https://github.com/allure-framework/allure-kotlin/commit/abb9d2d0034cbc99bf871e15548cda049561ab38) 
Also, here is some [examples](https://github.com/allure-framework/allure-kotlin/tree/master/samples/junit4-android), feel free to play with it.
